preload = /home/rogawa/.config/hypr/bg_images/ramu_chan.png

# モニターへの割り当て
# すべてのモニターに適用する場合はmonitorは空
wallpaper {
    monitor = 
    path = /home/rogawa/.config/hypr/bg_images/ramu_chan.png
    fit_mode = cover
}

splash = false
