# ------------------------------------------------------------------------------
# デフォルトシェルを変更
# ------------------------------------------------------------------------------
set-option -g default-shell "/usr/bin/zsh"
# set-option -g default-shell "${SHELL}"
# set -g default-command "/usr/bin/zsh"

# ------------------------------------------------------------------------------
# term gui colorを有効化
# ------------------------------------------------------------------------------
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:Tc"

# ------------------------------------------------------------------------------
# vim関連
# ------------------------------------------------------------------------------
## コピーモードでvi風のキーバインドを使える
setw -g mode-keys vi

# キー操作がvimと衝突しないように設定
# ------------------------------------------------------------------------------
# vim check-health のアドバイスによる
set-option -sg escape-time 10
set-option -g focus-events on

# ------------------------------------------------------------------------------
# ペインのステータス表示
# ------------------------------------------------------------------------------
# ペインのステータスを表示してボーダを目立たせる
set-option -g pane-border-status top
# ペインのステータスに表示する内容を変更(番号だけでスッキリ！)
set -g pane-border-format "[#P]"

# vim:ft=tmux :
