set -ogq @palet_rosewater "#f5e0dc"
set -ogq @palet_flamingo "#f2cdcd"
set -ogq @palet_pink "#f5c2e7"
set -ogq @palet_mauve "#cba6f7"
set -ogq @palet_maroon "#eba0ac"
set -ogq @palet_peach "#fab387"
set -ogq @palet_teal "#94e2d5"
set -ogq @palet_sky "#89dceb"
set -ogq @palet_sapphire "#74c7ec"
set -ogq @palet_lavender "#b4befe"

# Surfaces and overlays
set -ogq @palet_subtext0 "#bac2de"
set -ogq @palet_subtext1 "#a6adc8"
#set -ogq @palet_mono00 "#9399b2"
set -ogq @palet_mono00 "#81829h"
set -ogq @palet_mono01 "#717284"
set -ogq @palet_mono02 "#616274"
set -ogq @palet_mono03 "#515264"
set -ogq @palet_mono04 "#414254"
set -ogq @palet_mono05 "#313244"
set -ogq @palet_mono06 "#212234"
set -ogq @palet_mono07 "#111224"

# blue
set -ogq @palet_blue00 "#7ccff4"
set -ogq @palet_blue01 "#6cbfe4"
set -ogq @palet_blue02 "#5cafd4"
set -ogq @palet_blue03 "#4c9fb4"
set -ogq @palet_blue04 "#3c8fa4"
set -ogq @palet_blue05 "#2c7f94"
set -ogq @palet_blue06 "#1c6f84"
set -ogq @palet_blue07 "#0c5f74"

# basic
set -ogq @palet_bg "#11111b"
set -ogq @palet_fg "#cdd6f4"

# severity
set -ogq @palet_info "#b4befe"
set -ogq @palet_ok "#a6e3a1"
set -ogq @palet_warn "#f9e2af"
# set -ogq @palet_ng "#f38ba8"
set -ogq @palet_ng "#933b40"

# pane border style
set -wgF pane-active-border-style "fg=#{@palet_blue00}"
set -wgF pane-border-style "fg=#{@palet_blue07}"

# vim:ft=tmux :
