# ------------------------------------------------------------------------------
# カラーパレット読み込み
# ------------------------------------------------------------------------------
source -F "${HOME}/.config/tmux/palet.conf"

# ------------------------------------------------------------------------------
#  ステータスライン設定
# ------------------------------------------------------------------------------
# ステータスラインを上に表示
set-option -g status-position top
# 更新間隔
set -g status-interval 1 

# ステータスラインの背景透過
# set -g status-style bg=default

# ステータスラインのデフォルト色
set-option -gF status-bg "#{@palet_bg}"
set-option -gF status-fg "#{@palet_fg}"

# status left look and feel
set -g status-left-length 80
set -g status-left ""

# status right look and feel
set -g status-right-length 160
set -g status-right ""

# ------------------------------------------------------------------------------
# ステータスライン左側
# ------------------------------------------------------------------------------
set -g status-left ""
# セッション
set -ga status-left "#[bg=#{?client_prefix,#{E:@palet_ng},#{E:@palet_mono04}},fg=#{@palet_fg},bold] #S "
set -ga status-left "#[default] "
# window
### current window
set-window-option -g window-status-current-format "#[fg=#{@palet_fg},bg=#{@palet_blue07},bold] #I "
set-window-option -ga window-status-current-format "#[bg=#{@palet_mono06}] #[fg=#{@palet_mono01}]#F#[fg=#{@palet_fg}]#W "
set-window-option -ga window-status-current-format "#[default]"
## other window
set-window-option -g window-status-format "#[fg=#{@palet_fg},bg=#{@palet_mono04}] #I "
set-window-option -ga window-status-format "#[bg=#{@palet_mono06}] #[fg=#{@palet_mono01}]#F#[fg=#{@palet_fg}]#W "
set-window-option -ga window-status-format "#[default]"

# ------------------------------------------------------------------------------
# = ステータスライン右側
# ------------------------------------------------------------------------------
set -g status-right-length 160
set -g status-right ""

# cwd 󰝰
set -ga status-right "#[fg=#{@palet_sapphire},bg=#{@palet_mono06}]"
set -ga status-right "  "
set -ga status-right "#[fg=#{@palet_fg},bg=#{@palet_mono06}]"
set -ga status-right "#{?#{e|>:#{window_width},80},#{#{=/-32/…:#{pane_current_path}}},#{=/-12/…:#{b:pane_current_path}}}"
set -ga status-right "#[default]"

# gitブランチ
set -ga status-right "#[fg=#{@palet_maroon},bg=#{@palet_mono06}]"
set -ga status-right " 󰊤 "

set -ga status-right "#[fg=#{@palet_fg},bg=#{@palet_mono06}]"
set -ga status-right "#(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD)"
set -ga status-right "#[default]"

# アプリケーション
set -ga status-right "#[fg=#{@palet_teal},bg=#{@palet_mono06}]"
set -ga status-right " 󰆍 "

set -ga status-right "#[fg=#{@palet_fg},bg=#{@palet_mono06}]"
set -ga status-right "#{pane_current_command}"
set -ga status-right "#[default]"

# 時計
set -ga status-right "#[fg=#{@palet_lavender},bg=#{@palet_mono06}]"
set -ga status-right " 󰥔 "

set -ga status-right "#[fg=#{@palet_fg},bg=#{@palet_mono06}]"
set -ga status-right "%H:%M"
set -ga status-right "#[default]"

# custom vars ◢◣▄▀█
# set -g @custom_separator_left "◢"
# set -g @custom_separator_right "█"
# set -ogq @window_flags_icon_last " 󰖰" # -
# set -ogq @window_flags_icon_current " 󰖯" # *
# set -ogq @window_flags_icon_zoom " 󰁌" # Z
# set -ogq @window_flags_icon_mark " 󰃀" # M
# set -ogq @window_flags_icon_silent " 󰂛" # ~
# set -ogq @window_flags_icon_activity " 󱅫" # #
# set -ogq @window_flags_icon_bell " 󰂞" # !

# vim:ft=tmux :
